name: Ubuntu

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.github/workflows/mingw-build.yml'
    - '.github/workflows/macos-build.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.github/workflows/mingw-build.yml'
    - '.github/workflows/macos-build.yml'

jobs:
  build:
    runs-on: ${{ matrix.distro }}
    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        distro: [ubuntu-20.04, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2

    - name: Install SDL and deps
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install libsdl2-dev libjpeg-dev libwebp-dev libtiff5-dev libsdl2-image-dev libmikmod-dev libfishsound1-dev libsmpeg-dev liboggz2-dev libflac-dev libfluidsynth-dev libsdl2-mixer-dev libfreetype6-dev libsdl2-ttf-dev libsdl2-net-dev -y

    - name: Build source and tests
      run: python3 build.py
    
    - name: Run tests
      run: python3 build.py --run-tests

    #- name: Upload dist
      #uses: actions/upload-artifact@v2
      #with:
        #name: dist-Ubuntu-GCC
        #path: dist/
